// Writes src/source-sans-3.ts from the bundled TTF: `node packages/core/scripts/font-metrics.mjs`.
// Rerun it whenever packages/render/fonts/SourceSans3-Regular.ttf changes.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

const ttf = new URL("../../render/fonts/SourceSans3-Regular.ttf", import.meta.url);
const out = new URL("../src/source-sans-3.ts", import.meta.url);
const b = readFileSync(ttf);
const v = new DataView(b.buffer, b.byteOffset, b.byteLength);

const tables = {};
for (let i = 0; i < v.getUint16(4); i++) {
  const o = 12 + i * 16;
  tables[b.toString("latin1", o, o + 4)] = v.getUint32(o + 8);
}
const { head, hhea, hmtx, cmap } = tables;
const numberOfHMetrics = v.getUint16(hhea + 34);
// Glyphs past numberOfHMetrics repeat the last advance.
const advance = (glyph) => v.getUint16(hmtx + Math.min(glyph, numberOfHMetrics - 1) * 4);

// The (3, 10) subtable, format 12: groups of consecutive code points mapped to consecutive glyphs.
let sub;
for (let i = 0; i < v.getUint16(cmap + 2); i++) {
  const o = cmap + 4 + i * 8;
  if (v.getUint16(o) === 3 && v.getUint16(o + 2) === 10) sub = cmap + v.getUint32(o + 4);
}
if (sub === undefined || v.getUint16(sub) !== 12) throw new Error("No (3, 10) format 12 cmap.");
const advances = {};
for (let i = 0; i < v.getUint32(sub + 12); i++) {
  const o = sub + 16 + i * 12;
  const [start, end, glyph] = [v.getUint32(o), v.getUint32(o + 4), v.getUint32(o + 8)];
  for (let c = start; c <= end; c++) advances[c] = advance(glyph + c - start);
}

const metrics = {
  family: "Source Sans 3",
  unitsPerEm: v.getUint16(head + 18),
  ascender: v.getInt16(hhea + 4),
  descender: v.getInt16(hhea + 6),
  notdef: advance(0),
  advances,
};
writeFileSync(
  out,
  `// Generated by scripts/font-metrics.mjs from SourceSans3-Regular.ttf; do not edit.\n\n` +
    `/** Source Sans 3 Regular in font units: advance width by code point, and the hhea metrics. */\n` +
    `export const SOURCE_SANS_3 = ${JSON.stringify(metrics)} as const;\n`,
);
execFileSync("pnpm", ["biome", "format", "--write", out.pathname], { stdio: "inherit" });
